platform :ios, '8.0'
use_frameworks!

target 'FBAnnotationClusteringSwift_Example' do
	pod 'FBAnnotationClusteringSwift', :path => '../'
end

target 'FBAnnotationClusteringSwift_Tests' do
    pod 'FBAnnotationClusteringSwift', :path => '../'
end
